import Image from "next/image";
import Link from "next/link";
import Script from "next/script";

export const metadata = {
  title: "Programmable High Speed Refrigerated Centrifuge | AN Global Services",
  description:
    "Premium Programmable High Speed Refrigerated Centrifuge designed for molecular biology, clinical diagnostics, and advanced research. Features high-speed precision and CFC-free cooling. Setup by AN Global Services.",
  keywords: [
    "High Speed Refrigerated Centrifuge",
    "Programmable Refrigerated Centrifuge",
    "High Speed Cooling Centrifuge",
    "Laboratory Refrigerated Centrifuge",
    "Clinical Centrifuge Machine",
    "High RPM Refrigerated Centrifuge",
    "Medical Centrifuge Equipment",
    "AN Global Services laboratory equipment",
  ],
  alternates: {
    canonical: "https://www.anglobalservices.com/programmable-high-speed-refrigerated-centrifuge",
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function RefrigeratedCentrifugePage() {
  return (
    <main className="w-full bg-gray-50 min-h-screen">
      {/* Schema Markup */}
      <Script id="refrigerated-centrifuge-schema" type="application/ld+json" strategy="afterInteractive">
        {`
        {
          "@context": "https://schema.org",
          "@graph": [
            {
              "@type": "Product",
              "name": "Programmable High Speed Refrigerated Centrifuge",
              "description": "Premium Programmable High Speed Refrigerated Centrifuge designed for molecular biology, clinical diagnostics, and advanced research. Features a high-speed brushless motor and ultra-precise temperature control.",
              "image": "https://www.anglobalservices.com/equipment/centrifuge/programmable-high-speed-refrigerated-centrifuge.webp",
              "brand": {
                "@type": "Brand",
                "name": "AN Global Services"
              },
              "offers": {
                "@type": "Offer",
                "availability": "https://schema.org/InStock",
                "seller": {
                  "@type": "Organization",
                  "name": "AN Global Services"
                }
              }
            },
            {
              "@type": "FAQPage",
              "mainEntity": [{
                "@type": "Question",
                "name": "What is a refrigerated centrifuge used for?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "A refrigerated centrifuge is essential for separating temperature-sensitive biological samples, such as DNA, RNA, proteins, and live cells. The built-in refrigeration system prevents heat degradation generated by high-speed friction."
                }
              },{
                "@type": "Question",
                "name": "What is the maximum speed of a high-speed refrigerated centrifuge?",
                "acceptedAnswer": {
                  "@type": "Answer",
                  "text": "High-speed refrigerated centrifuges typically reach maximum speeds between 16,000 RPM to 20,000 RPM, depending on the rotor configuration, delivering relative centrifugal forces (RCF) required for sub-cellular fractionations."
                }
              }]
            }
          ]
        }
        `}
      </Script>

      {/* Hero Section */}
      <section className="relative w-full h-64 md:h-72">
        <Image
          src="/service/pages-of-services-dash-1.webp"
          alt="High Speed Refrigerated Centrifuge Laboratory Equipment"
          fill
          priority
          className="object-cover"
        />
        <div className="absolute inset-0 bg-[#0a3d62]/40 flex items-center justify-center text-center">
          <div className="max-w-6xl mx-auto px-4">
            <h1 className="text-white text-3xl md:text-4xl font-extrabold tracking-wide drop-shadow-[0_4px_4px_rgba(0,0,0,0.9)] uppercase">
              PROGRAMMABLE HIGH SPEED REFRIGERATED CENTRIFUGE
            </h1>
          </div>
        </div>
      </section>

      {/* Main Product Card Section */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 py-12" id="product-overview">
        <div className="rounded-3xl border border-gray-200 bg-white overflow-hidden shadow-xl">
          <div className="flex flex-col lg:flex-row h-full">
            
            {/* Image Side */}
            <div className="lg:w-[40%] relative flex items-center justify-center p-8 bg-gradient-to-br from-blue-50 to-white border-b lg:border-b-0 lg:border-r border-gray-100 min-h-[400px]">
              <div className="absolute inset-0 opacity-10 mix-blend-multiply" style={{ backgroundImage: 'radial-gradient(circle at 2px 2px, #0075B6 1px, transparent 0)', backgroundSize: '16px 16px' }}></div>
              <div className="relative w-full h-full max-w-[400px] aspect-[4/5]">
                <Image
                  src="/equipment/centrifuge/programmable-high-speed-refrigerated-centrifuge.webp"
                  alt="Programmable High Speed Refrigerated Centrifuge Equipment"
                  fill
                  className="object-contain drop-shadow-2xl hover:scale-105 transition-transform duration-500"
                  sizes="(max-width: 1024px) 100vw, 40vw"
                  priority
                />
              </div>
            </div>

            {/* Content Side */}
            <div className="lg:w-[60%] p-8 md:p-12 flex flex-col justify-center">
              <h2 className="text-2xl md:text-3xl font-black text-[#0a192f] mb-4">
                About the Product
              </h2>
              <div className="w-16 h-1.5 bg-[#0075B6] rounded-full mb-6"></div>
              
              <div className="space-y-5 text-gray-700 text-base md:text-lg leading-relaxed font-medium">
                <p>
                  The <strong className="text-[#0075B6]">Programmable High Speed Refrigerated Centrifuge</strong> is a state-of-the-art laboratory instrument engineered for the most demanding molecular biology, biochemistry, and clinical applications.
                </p>
                <p>
                  When spinning samples at extreme speeds up to 20,000 RPM, air friction naturally generates immense heat. This advanced centrifuge utilizes a robust, CFC-free refrigeration system to combat this, ensuring your temperature-sensitive samples remain perfectly preserved at steady, low temperatures throughout the entire run.
                </p>
                <div className="bg-blue-50/80 border-l-4 border-[#0075B6] p-5 rounded-r-lg mt-6 shadow-sm">
                  <h3 className="text-[#0a192f] font-bold text-lg mb-2 flex items-center gap-2">
                    <span className="text-xl">⚙️</span> Complete Setup by AN Global Services
                  </h3>
                  <p className="text-gray-700 text-sm md:text-base">
                    Operating high-speed laboratory equipment requires precision and extreme safety. Our team provides <strong className="text-[#0a192f]">comprehensive end-to-end solutions</strong>. We don't just deliver the equipment; we fully install it, calibrate the rotors, and train your staff on how to safely conduct high-speed operations.
                  </p>
                </div>
              </div>

              <div className="mt-8 flex flex-wrap gap-4">
                <Link
                  href="/contact-us"
                  className="bg-[#0075B6] hover:bg-[#005a8f] text-white px-8 py-3.5 rounded-lg font-bold transition-all shadow-lg hover:shadow-xl hover:-translate-y-0.5 text-center flex-1 sm:flex-none"
                >
                  Request a Quote & Setup
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Operating Principle Section (How It Works) */}
      <section className="bg-white py-16 border-t border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h2 className="text-3xl font-black text-[#0a192f] mb-4">How the Centrifugation Works</h2>
              <div className="w-16 h-1.5 bg-[#0075B6] rounded-full mb-8"></div>
              <p className="text-gray-600 text-lg mb-8 leading-relaxed">
                Conducting high-speed separation is a straightforward but highly controlled process. Here is how the equipment perfectly isolates your samples:
              </p>
              
              <div className="space-y-6">
                <div className="flex gap-4">
                  <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center text-[#0075B6] font-bold text-xl">1</div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-900 mb-2">Preparation & Programming</h3>
                    <p className="text-gray-600 leading-relaxed">Samples are carefully balanced and loaded into the rotor. Using the microprocessor panel, the operator sets the specific RPM/RCF, time, and target temperature (e.g., 4°C) for the protocol.</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center text-[#0075B6] font-bold text-xl">2</div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-900 mb-2">High-Speed Rotation</h3>
                    <p className="text-gray-600 leading-relaxed">The brushless DC motor smoothly accelerates the rotor to the set speed. The built-in refrigeration system simultaneously activates, neutralizing any heat generated by air friction in the chamber.</p>
                  </div>
                </div>
                <div className="flex gap-4">
                  <div className="flex-shrink-0 w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center text-[#0075B6] font-bold text-xl">3</div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-900 mb-2">Separation & Extraction</h3>
                    <p className="text-gray-600 leading-relaxed">At the end of the timer, the centrifuge safely decelerates. The dense particles form a solid pellet at the bottom of the tube, while the lighter liquid supernatant remains clearly separated at the top.</p>
                  </div>
                </div>
              </div>
            </div>
            
            <div className="bg-gray-50 rounded-2xl p-8 border border-gray-200 shadow-inner">
              <h3 className="text-2xl font-bold text-gray-900 mb-6 border-b border-gray-200 pb-4">Key Users & Facilities</h3>
              <ul className="space-y-5">
                <li className="flex items-start gap-4">
                  <div className="mt-1 text-2xl">🧬</div>
                  <div>
                    <strong className="block text-lg text-gray-900">Molecular Biology Labs</strong>
                    <span className="text-gray-600">Used daily to extract DNA/RNA and purify temperature-sensitive cellular components.</span>
                  </div>
                </li>
                <li className="flex items-start gap-4">
                  <div className="mt-1 text-2xl">🏥</div>
                  <div>
                    <strong className="block text-lg text-gray-900">Clinical Diagnostics</strong>
                    <span className="text-gray-600">Utilized to rapidly separate blood serum or plasma for advanced pathology and diagnostic testing.</span>
                  </div>
                </li>
                <li className="flex items-start gap-4">
                  <div className="mt-1 text-2xl">💊</div>
                  <div>
                    <strong className="block text-lg text-gray-900">Pharmaceutical R&D</strong>
                    <span className="text-gray-600">Essential for drug development processes, enzyme assays, and precise biochemical fractionations.</span>
                  </div>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </section>

      {/* Detailed Specifications Cards */}
      <section className="bg-gray-100 py-16 border-t border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-black text-[#0a192f] mb-4">Equipment Features & Specs</h2>
            <p className="text-gray-600 max-w-2xl mx-auto text-lg">Built strictly for safety, precision, and ease of use in advanced laboratory environments.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            
            {/* Card 1 */}
            <div className="bg-white rounded-2xl p-8 shadow-md border border-gray-100 hover:shadow-xl transition-shadow group relative overflow-hidden">
              <div className="absolute top-0 right-0 w-24 h-24 bg-blue-50 rounded-bl-full -z-0 group-hover:scale-110 transition-transform"></div>
              <div className="relative z-10">
                <div className="w-12 h-12 bg-blue-100 text-[#0075B6] rounded-xl flex items-center justify-center text-2xl mb-6 shadow-sm">
                  🎛️
                </div>
                <h3 className="text-xl font-extrabold text-[#0a192f] mb-3">Precision Control</h3>
                <ul className="space-y-3 text-gray-600 font-medium text-sm">
                  <li className="flex items-start gap-2"><span className="text-[#0075B6] mt-0.5">✔</span> <strong>Microprocessor:</strong> Fully programmable system to store and recall specific run protocols.</li>
                  <li className="flex items-start gap-2"><span className="text-[#0075B6] mt-0.5">✔</span> <strong>Digital LCD/LED Display:</strong> Clear readouts of Speed, RCF, Time, and Temperature.</li>
                  <li className="flex items-start gap-2"><span className="text-[#0075B6] mt-0.5">✔</span> <strong>Accel/Decel Rates:</strong> Variable acceleration and deceleration curves to protect fragile samples.</li>
                </ul>
              </div>
            </div>

            {/* Card 2 */}
            <div className="bg-white rounded-2xl p-8 shadow-md border border-gray-100 hover:shadow-xl transition-shadow group relative overflow-hidden">
              <div className="absolute top-0 right-0 w-24 h-24 bg-red-50 rounded-bl-full -z-0 group-hover:scale-110 transition-transform"></div>
              <div className="relative z-10">
                <div className="w-12 h-12 bg-red-100 text-red-600 rounded-xl flex items-center justify-center text-2xl mb-6 shadow-sm">
                  🛡️
                </div>
                <h3 className="text-xl font-extrabold text-[#0a192f] mb-3">Redundant Safety</h3>
                <ul className="space-y-3 text-gray-600 font-medium text-sm">
                  <li className="flex items-start gap-2"><span className="text-red-500 mt-0.5">✔</span> <strong>Electronic Lid Interlock:</strong> Secures the chamber completely, preventing opening while the rotor is spinning.</li>
                  <li className="flex items-start gap-2"><span className="text-red-500 mt-0.5">✔</span> <strong>Imbalance Detection:</strong> Automatically halts operation if tubes are loaded unevenly.</li>
                  <li className="flex items-start gap-2"><span className="text-red-500 mt-0.5">✔</span> <strong>Over-Speed Protection:</strong> Fault alarms and auto-shutdown if maximum RPM limits are exceeded.</li>
                </ul>
              </div>
            </div>

            {/* Card 3 */}
            <div className="bg-white rounded-2xl p-8 shadow-md border border-gray-100 hover:shadow-xl transition-shadow group relative overflow-hidden">
              <div className="absolute top-0 right-0 w-24 h-24 bg-green-50 rounded-bl-full -z-0 group-hover:scale-110 transition-transform"></div>
              <div className="relative z-10">
                <div className="w-12 h-12 bg-green-100 text-green-700 rounded-xl flex items-center justify-center text-2xl mb-6 shadow-sm">
                  🏗️
                </div>
                <h3 className="text-xl font-extrabold text-[#0a192f] mb-3">Rugged Build Quality</h3>
                <ul className="space-y-3 text-gray-600 font-medium text-sm">
                  <li className="flex items-start gap-2"><span className="text-green-600 mt-0.5">✔</span> <strong>Brushless DC Motor:</strong> Maintenance-free, quiet operation with zero carbon dust.</li>
                  <li className="flex items-start gap-2"><span className="text-green-600 mt-0.5">✔</span> <strong>Stainless Steel Chamber:</strong> Corrosion-resistant interior designed for easy cleaning.</li>
                  <li className="flex items-start gap-2"><span className="text-green-600 mt-0.5">✔</span> <strong>CFC-Free Refrigeration:</strong> Eco-friendly compressor for highly efficient, rapid cooling.</li>
                </ul>
              </div>
            </div>

            {/* Card 4 - Full Width Specs */}
            <div className="bg-[#0a192f] rounded-2xl p-8 shadow-lg md:col-span-2 lg:col-span-3 mt-4 relative overflow-hidden">
              <div className="absolute -right-20 -top-20 w-64 h-64 bg-white/5 rounded-full blur-3xl"></div>
              <div className="relative z-10">
                <h3 className="text-2xl font-black text-white mb-6 border-b border-white/20 pb-4">Technical Specifications & Build</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
                  <div>
                    <div className="text-blue-300 text-xs font-bold uppercase tracking-wider mb-1">Max Speed</div>
                    <div className="text-white font-semibold">16,000 - 20,000 RPM (Rotor Dep.)</div>
                  </div>
                  <div>
                    <div className="text-blue-300 text-xs font-bold uppercase tracking-wider mb-1">Temperature Range</div>
                    <div className="text-white font-semibold">-20°C to +40°C</div>
                  </div>
                  <div>
                    <div className="text-blue-300 text-xs font-bold uppercase tracking-wider mb-1">Max RCF</div>
                    <div className="text-white font-semibold">Up to 27,800 x g</div>
                  </div>
                  <div>
                    <div className="text-blue-300 text-xs font-bold uppercase tracking-wider mb-1">Timer Range</div>
                    <div className="text-white font-semibold">1 min to 99 hrs 59 mins</div>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      </section>

      {/* Maintenance & Compliance Section */}
      <section className="bg-white py-16 border-t border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">
          <div className="mb-12">
            <h2 className="text-3xl font-black text-[#0a192f] mb-4">Comprehensive Maintenance & Calibration Guide</h2>
            <div className="w-16 h-1.5 bg-[#0075B6] rounded-full mb-6"></div>
            <p className="text-gray-600 text-lg max-w-3xl leading-relaxed">
              Operating high-speed rotational equipment requires strict maintenance protocols to ensure absolute safety and precise experimental results. AN Global Services provides complete guidance on the following operational requirements:
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="border-l-4 border-[#0075B6] pl-6 py-2 bg-gray-50 rounded-r-xl">
              <h4 className="text-lg font-bold text-gray-900 mb-3 uppercase tracking-wide">Routine Inspections</h4>
              <ul className="list-disc list-inside text-gray-600 space-y-2">
                <li>Check the rotor and buckets for scratches or signs of metal fatigue before every run.</li>
                <li>Ensure the chamber is free from condensation or spilled samples.</li>
                <li>Wipe down the stainless steel chamber to remove debris.</li>
              </ul>
            </div>
            
            <div className="border-l-4 border-purple-500 pl-6 py-2 bg-gray-50 rounded-r-xl">
              <h4 className="text-lg font-bold text-gray-900 mb-3 uppercase tracking-wide">Safety Testing</h4>
              <ul className="list-disc list-inside text-gray-600 space-y-2">
                <li><strong>Interlock Check:</strong> Verify the electronic lid lock is securely engaging.</li>
                <li><strong>Balance Test:</strong> Routinely check the imbalance detection sensors by safely mimicking an unaligned load at low speeds.</li>
              </ul>
            </div>

            <div className="border-l-4 border-green-500 pl-6 py-2 bg-gray-50 rounded-r-xl">
              <h4 className="text-lg font-bold text-gray-900 mb-3 uppercase tracking-wide">Annual Servicing</h4>
              <ul className="list-disc list-inside text-gray-600 space-y-2">
                <li>Official calibration of the microprocessor speed and temperature sensors.</li>
                <li>Professional inspection of the brushless motor and drive shaft.</li>
                <li>Servicing of the CFC-free refrigeration compressor unit.</li>
              </ul>
            </div>
          </div>
        </div>
      </section>
      
      {/* FAQ Section */}
      <section className="bg-white py-16 border-t border-gray-200" id="faqs">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[#0a192f] mb-4">Frequently Asked Questions</h2>
            <div className="w-16 h-1 bg-[#0075B6] rounded-full mx-auto mb-6"></div>
            <p className="text-gray-500 text-lg">Learn more about our specialized refrigerated centrifuges.</p>
          </div>

          <div className="space-y-4">
            <details className="group bg-gray-50/50 rounded-xl border border-gray-200 overflow-hidden cursor-pointer open:bg-white open:shadow-md transition-all duration-300">
              <summary className="flex items-center justify-between p-5 font-semibold text-gray-900 group-open:text-[#0075B6]">
                Why choose a refrigerated centrifuge over a ventilated one?
                <span className="transition duration-300 group-open:rotate-90 text-gray-400 group-open:text-[#0075B6]">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7"></path></svg>
                </span>
              </summary>
              <div className="px-5 pb-5 text-gray-600 pt-2 border-t border-gray-100">
                When spinning samples at high speeds (above 10,000 RPM), significant heat is generated due to air friction. A ventilated centrifuge will cause the sample temperature to rise, which can denature proteins, degrade nucleic acids, and destroy live cells. A refrigerated centrifuge actively cools the chamber, keeping sensitive biological samples safely at 4°C despite the friction.
              </div>
            </details>
            
            <details className="group bg-gray-50/50 rounded-xl border border-gray-200 overflow-hidden cursor-pointer open:bg-white open:shadow-md transition-all duration-300">
              <summary className="flex items-center justify-between p-5 font-semibold text-gray-900 group-open:text-[#0075B6]">
                Can I use different rotors with this centrifuge?
                <span className="transition duration-300 group-open:rotate-90 text-gray-400 group-open:text-[#0075B6]">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7"></path></svg>
                </span>
              </summary>
              <div className="px-5 pb-5 text-gray-600 pt-2 border-t border-gray-100">
                Yes. Our high-speed refrigerated centrifuges are highly versatile and compatible with a wide range of interchangeable rotors. This includes fixed-angle rotors for high-speed pelleting (e.g., 1.5/2.0 mL micro-tubes, 15/50 mL conical tubes) and swing-out rotors for lower-speed density gradient separations.
              </div>
            </details>

            <details className="group bg-gray-50/50 rounded-xl border border-gray-200 overflow-hidden cursor-pointer open:bg-white open:shadow-md transition-all duration-300">
              <summary className="flex items-center justify-between p-5 font-semibold text-gray-900 group-open:text-[#0075B6]">
                What does 'Programmable' mean in this context?
                <span className="transition duration-300 group-open:rotate-90 text-gray-400 group-open:text-[#0075B6]">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7"></path></svg>
                </span>
              </summary>
              <div className="px-5 pb-5 text-gray-600 pt-2 border-t border-gray-100">
                Programmable centrifuges feature a microprocessor memory system that allows lab technicians to save specific run protocols. Users can program precise parameters for Speed, RCF, Temperature, Run Time, and Accel/Decel curves, ensuring absolute reproducibility across multiple experiments without manual reentry.
              </div>
            </details>

            <details className="group bg-gray-50/50 rounded-xl border border-gray-200 overflow-hidden cursor-pointer open:bg-white open:shadow-md transition-all duration-300">
              <summary className="flex items-center justify-between p-5 font-semibold text-gray-900 group-open:text-[#0075B6]">
                What safety features are included?
                <span className="transition duration-300 group-open:rotate-90 text-gray-400 group-open:text-[#0075B6]">
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 5l7 7-7 7"></path></svg>
                </span>
              </summary>
              <div className="px-5 pb-5 text-gray-600 pt-2 border-t border-gray-100">
                Our equipment features multi-level safety mechanisms including an electronic lid interlock (prevents opening while spinning), imbalance detection, over-temperature protection, and over-speed fault alarms to ensure complete operator safety.
              </div>
            </details>
          </div>
        </div>
      </section>
    </main>
  );
}
