export default function sitemap() {
const baseUrl = 'https://www.anglobalservices.com'

  const pages = [
    '',
    'aboutus',
    'blogs',
    'blogs/bis-isi-mark-product-certificate-guide',
    'blogs/how-to-get-bis-crs-certification-for-electronic-products',
    'contact-us',
    'bee_services',
    'bis-crs-registration-electronic-products',
    'bis-isi-mark-certification-furniture-plywood',
    'bis-hallmarking-setup-services',
    'bis-isi-mark-certification-medical-products',
    'bis-isi-mark-certification-plastic-products',
    'bis-isi-mark-certification-concrete-products',
    'bis-isi-mark-certification-hardware-products',
    'bis-isi-mark-certification-electronics-products',
    'bis-isi-mark-certification-home-appliances-kitchen-products',
    'isi-products/isi-mark-certification-for-disposable-baby-diaper-is-17509',
    'isi-products/isi-mark-certification-for-sanitary-napkin-5405',
    'isi-products/isi-mark-certification-for-disposable-adult-diaper-17508',
    'isi-products/isi-certification-for-evaporative-air-coolers-desert-coolers-3315',
    'isi-products/isi-certification-for-electric-ceiling-type-fan-374',
    'isi-products/isi-certification-for-domestic-pressure-cookers-2347',
    'isi-products/isi-certification-for-upvc-pipes-for-water-supplies-4985',
    'isi-products/isi-certification-high-density-polyethylene-pipes-4984',
    'jewellery-registration',
    'calibration-certificate',
    'chemicals-petrochemicals',
    'epr-registration-services',
    'eqipmentforsolar',
    'equipmentforfootwear',
    'eqipmentsforleaser',
    'equipmentforgold',
    'equipmentfortoy',
    'fssai-registration-services',
    'foreign-manufacturers-certification-scheme-fmcs',
    'footwear',
    'gem_services',
    'hallmarking',
    'iso-certification-services',
    'bis-isi-mark-certification',
    'lab_servces',
    'latest_updates',
    'news-updates',
    'msme-nsic-registration',
    'nabl-accreditation-services',
    'notifi_bolts_nuts_order',
    'solar_services',
    'bis-registration-for-solar-panels',
    'solar-equipment',
    'solar-panel-plant-setup',
    'steel-products',
    'term-conditions',
    'testing_footwear',
    'testing_gold',
    'testing_solar_panel',
    'testing-toys',
    'trademark-registration-services',
    'training-services-national-international',
    'wpc-certification-services',

  ]

  return pages.map((page) => ({
    url: `${baseUrl}/${page}`,
    lastModified: new Date(),
    changeFrequency: 'daily',
    priority: page === '' ? 1 : 0.8,
  }))
}
