

export const isiProductsList = [
    { sNo: 1, isNo: "IS 3312", name: "Adjustable Steel Shelving Cabinets", slug: "isi-certificate-adjustable-steel-shelving-cabinets" },
    { sNo: 2, isNo: "IS 7092 : Part 2", name: "Aluminium Alloy Extruded Tubes for Irrigation", slug: "isi-certificate-aluminium-alloy-extruded-tubes-for-irrigation-purposes" },
    { sNo: 3, isNo: "IS 7092 : Part 1", name: "Aluminium Alloy Welded Tubes for Irrigation", slug: "isi-certificate-aluminium-alloy-tubes-for-irrigation-purposes-welded-tubes" },
    { sNo: 4, isNo: "IS 15392", name: "Aluminium Bare Foil for Food Packaging", slug: "isi-certificate-aluminium-and-aluminium-alloy-bare-foil-for-food-packaging" },
    { sNo: 5, isNo: "IS 16011", name: "Aluminium Foil for Pharmaceutical Packaging", slug: "isi-certificate-aluminium-and-aluminium-alloy-foil-for-pharmaceutical-packaging" },
    { sNo: 6, isNo: "IS 737", name: "Aluminium Sheet and Strip", slug: "isi-certificate-aluminium-and-aluminium-alloy-sheet-and-strip" },
    { sNo: 7, isNo: "IS 1258", name: "Bayonet Lamp Holders", slug: "isi-certificate-bayonet-lamp-holders-1258" },
    { sNo: 8, isNo: "IS 17681", name: "Bottled Water Dispensers", slug: "isi-certificate-bottled-water-dispensers" },
    { sNo: 9, isNo: "IS 17636", name: "Bunk Beds", slug: "isi-certificate-bunk-beds-17636" },
    { sNo: 10, isNo: "IS 7872", name: "Deep Freezers", slug: "isi-certificate-deep-freezers" },
    { sNo: 11, isNo: "IS 4250", name: "Domestic Electric Food Mixers", slug: "isi-certificate-domestic-electric-food-mixers" },
    { sNo: 12, isNo: "IS 4246", name: "Domestic Gas Stoves", slug: "isi-certificate-domestic-gas-stove" },
    { sNo: 13, isNo: "IS 5484", name: "EC Grade Aluminium Rods", slug: "isi-certificate-ec-grade-aluminium-rod-produced-by-continuous-casting-and-rolling" },
    { sNo: 14, isNo: "IS 17545", name: "Wall Putty", slug: "isi-certificate-for-wall-putty-17545" },
    { sNo: 15, isNo: "IS 17635", name: "Furniture Beds", slug: "isi-certificate-furniture-beds" },
    { sNo: 16, isNo: "IS 17634", name: "Furniture Storage Units", slug: "isi-certificate-furniture-storage-units" },
    { sNo: 17, isNo: "IS 17633", name: "Furniture Tables and Desks", slug: "isi-certificate-furniture-tables-and-desks" },
    { sNo: 18, isNo: "IS 12615", name: "Three-Phase AC Motors", slug: "isi-certificate-line-operated-three-phase-ac-motors" },
    { sNo: 19, isNo: "IS 17630", name: "Medical Textiles: Bedsheets and Pillow Covers", slug: "isi-certificate-medical-textile-bedsheet-and-pillow-cover" },
    { sNo: 20, isNo: "IS 9763", name: "Plastic Bib Taps and Valves", slug: "isi-certificate-plastics-bib-taps-pillar-taps-angle-stop-valves" },
    { sNo: 21, isNo: "IS 4151", name: "Protective Helmets for Two-Wheelers", slug: "isi-certificate-protective-two-wheelers-helmets" },
    { sNo: 22, isNo: "IS 694", name: "PVC Insulated Cables", slug: "isi-certificate-pvc-insulated-cables-694" },
    { sNo: 23, isNo: "IS 15644", name: "Safety of Electric Toys", slug: "isi-certificate-safety-of-electric-toys-15644" },
    { sNo: 24, isNo: "IS 12817", name: "Stainless Steel Butt Hinges", slug: "isi-certificate-stainless-steel-butt-hinges" },
    { sNo: 25, isNo: "IS 2082", name: "Electric Water Heaters", slug: "isi-certificate-stationary-storage-type-electric-water-heaters" },
    { sNo: 26, isNo: "IS 2266", name: "Steel Wire Ropes", slug: "isi-certificate-steel-wire-ropes-for-general-engineering-purposes" },
    { sNo: 27, isNo: "IS 733", name: "Wrought Aluminium Bars and Rods", slug: "isi-certificate-wrought-aluminium-and-aluminium-alloy-bars-rods" },
    { sNo: 28, isNo: "IS 5082", name: "Wrought Aluminium for Electrical Purposes", slug: "isi-certificate-wrought-aluminium-and-aluminium-alloy-electrical-purposes" },
    { sNo: 29, isNo: "IS 736", name: "Wrought Aluminium Plates", slug: "isi-certificate-wrought-aluminium-and-aluminium-alloy-plate" },
    { sNo: 30, isNo: "IS 739", name: "Wrought Aluminium Wires", slug: "isi-certificate-wrought-aluminum-and-aluminum-alloys-wire-for-general-engineering-purposes" },
    { sNo: 31, isNo: "IS 14333", name: "HDPE Pipes for Sewerage", slug: "isi-certification-for-high-density-polyethylene-pipes-for-sewerage-14333" },
    { sNo: 32, isNo: "IS 7834", name: "Injection Moulded PVC Socket Fittings", slug: "isi-certification-for-injection-moulded-pvc-socket-fittings-7834" },
    { sNo: 33, isNo: "IS 710", name: "Marine Plywood", slug: "isi-certification-for-marine-plywood" },
    { sNo: 34, isNo: "IS 15328", name: "Non-Pressure UPVC Pipes", slug: "isi-certification-for-non-pressure-upvc-pipes-15328" },
    { sNo: 35, isNo: "IS 9473", name: "Respiratory Protective Devices (Masks)", slug: "isi-certification-for-respiratory-protective-devices-filtering-half-masks-9473" },
    { sNo: 36, isNo: "IS 3589", name: "Steel Pipes for Water and Sewage", slug: "isi-certification-for-steel-pipes-for-water-sewage-3589" },
    { sNo: 37, isNo: "IS 1239 : Part 1", name: "Steel Tubes and Tubulars", slug: "isi-certification-for-steel-tubes-tubulars-part-1-1239" },
    { sNo: 38, isNo: "IS 16289", name: "Surgical Face Masks", slug: "isi-certification-for-surgical-face-masks-16289" },
    { sNo: 39, isNo: "IS 13592", name: "UPVC Pipes for Soil and Waste", slug: "isi-certification-for-upvc-pipes-for-soil-and-waste-discharge-13592" },
    { sNo: 40, isNo: "IS 4985", name: "UPVC Pipes for Water Supplies", slug: "isi-certification-for-upvc-pipes-for-water-supplies-4985" },
    { sNo: 41, isNo: "IS 17632", name: "Furniture Chairs and Stools", slug: "isi-certification-furniture-general-purpose-chairs-and-stools-17632" },
    { sNo: 42, isNo: "IS 651", name: "Glazed Stoneware Pipes", slug: "isi-certification-glazed-stoneware-pipes-651" },
    { sNo: 43, isNo: "IS 4984", name: "HDPE Pipes", slug: "isi-certification-high-density-polyethylene-pipes-4984" },
    { sNo: 44, isNo: "IS 17631", name: "Office Work Chairs", slug: "isi-certification-office-work-chair-17631" },
    { sNo: 45, isNo: "IS 1293", name: "Plugs and Socket Outlets", slug: "isi-certification-plugs-and-socket-outlets-1293" },
    { sNo: 46, isNo: "IS 303", name: "General Purpose Plywood", slug: "isi-certification-plywood-for-general-purposes" },
    { sNo: 47, isNo: "IS 458", name: "Precast Concrete Pipes", slug: "isi-certification-precast-concrete-pipes-458" },
    { sNo: 48, isNo: "IS 17508", name: "Disposable Adult Diapers", slug: "isi-mark-certification-for-disposable-adult-diaper-17508" },
    { sNo: 49, isNo: "IS 17509", name: "Disposable Baby Diapers", slug: "isi-mark-certification-for-disposable-baby-diaper-17509" },
    { sNo: 50, isNo: "IS 5405", name: "Sanitary Napkins", slug: "isi-mark-certification-for-sanitary-napkin-5405" },
    { sNo: 51, isNo: "IS 15778", name: "CPVC Pipes for Hot and Cold Water", slug: "isi-certification-for-cpvc-pipes-for-potable-hot-and-cold-water-distribution-supplies-15778" },
    { sNo: 52, isNo: "IS 13422", name: "Disposable Surgical Rubber Gloves", slug: "isi-certification-for-disposable-surgical-rubber-gloves-13422" },
    { sNo: 53, isNo: "IS 2347", name: "Domestic Pressure Cookers", slug: "isi-certification-for-domestic-pressure-cookers-2347" },
    { sNo: 54, isNo: "IS 374", name: "Electric Ceiling Fans", slug: "isi-certification-for-electric-ceiling-type-fan-374" },
    { sNo: 55, isNo: "IS 3315", name: "Evaporative Air Coolers (Desert Coolers)", slug: "isi-certification-for-evaporative-air-coolers-desert-coolers-3315" }
];